services:
  back-end:
    build:
      dockerfile: Dockerfile
      context: ./back-end
    ports:
      - '5252:5252'
    image: softy-pinko-back-end:task5

  front-end:
    build:
      dockerfile: Dockerfile
      context: ./front-end
    ports:
      - '9000:9000'
    image: softy-pinko-front-end:task5
    depends_on:
      - back-end

  proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - '80:80'
    image: softy-pinko-proxy:task5
    depends_on:
      - back-end
      - front-end
